export { CustomCarousel } from './CustomCarousel';
export { ContentLoading } from './ContentLoading';
export { TitleComponent } from './product-detail-component/TitleComponent';
export { CustomModal } from './CustomModal';
export { SellerComponent } from './product-detail-component/SellerComponent';
export { DescriptionComponent } from './product-detail-component/DescriptionComponent';
export { ProductCarouselComponent } from './product-detail-component/ProductCarouselComponent';

// export { CouseDetailHighlight } from './CouseDetailHighlight';
// export { CourseDetailContent } from './CourseDetailContent';
// export { CourseDetailHero } from './CourseDetailHero';
// export { CourseVideoSidebar } from './CourseVideoSidebar';
// export { CourseVideoHeaderComponent } from './CourseVideoHeaderComponent';
// export { CourseVideoMainContent } from './CourseVideoMainContent';
// export { CourseAboutComponent } from './CourseAboutComponent';
// export { Courses } from './InstructorProfile/Coures';
// export { ProfilePage } from './InstructorProfile/ProfilePage';
// export { ProfilePhoto } from './InstructorProfile/ProfilePhoto';
// export { LogoLink } from './LoginSignup/LogoLink';
// export { AccountSecurity } from './GuestProfile/AccountSecurity';
// export { ChangePassword } from './GuestProfile/ChangePassword';
// export { ResendCodeButton } from './GuestProfile/ResendCodeButton';
// export { Category } from './MaketPlace/Category';
// export { Products } from './MaketPlace/Products';
// export { SearchList } from './MaketPlace/SearchList';
// export { SortBy } from './MaketPlace/SortBy';
// export { CategoryFilter } from './SearchResult/CategoryFilter';
// export { CustomFormController } from './SearchResult/CutomFormController';
// export { FilterByOther } from './SearchResult/FilterByOther';
// export { SortByFilter } from './SearchResult/SortByFilter';
// export { CustomRadio } from './SearchResult/CustomRadio';
// export { ExpandableText } from './SearchResult/ExpandableText';
// export { FilterByRating } from './SearchResult/FilterByRating';
// export { FilterByPrice } from './SearchResult/FilterByPrice';
